### ISSUE TITLE
redis hangs on fresh install

### ISSUE THREAD

**Issue by brettswift** [fsalum/puppet-redis#45]
I've tried this with and without the system_sysctl option.   Both will hang.   

Puppet Code:

``` puppet

  require epel

  class { 'redis':
    system_sysctl => true
  }

  Class['epel']->
  Class['redis']

```

Last few lines of puppet output before it hangs: 

``` bash
==> masterofpuppets: Info: /Stage[main]/Redis/File[/etc/redis.conf]: Filebucketed /etc/redis.conf to puppet with sum 1b59697dc32ec93399fb1828553e5f97
==> masterofpuppets: Notice: /Stage[main]/Redis/File[/etc/redis.conf]/content: content changed '{md5}1b59697dc32ec93399fb1828553e5f97' to '{md5}68b329da9893e34099c7d8ad5cb9c940'
==> masterofpuppets: Info: /Stage[main]/Redis/File[/etc/redis.conf]: Scheduling refresh of Service[redis]
==> masterofpuppets: Notice: /Stage[main]/Redis/File[/var/lib/redis/]/group: group changed 'root' to 'redis'

--> hangs here

```

If I kill the puppet process and run it again,  it completes very quickly. 

I saw the same issue raised in ticket #38.    

I quite like this module, as it seems quite feature complete, but for the time being I may have to start using a different one if I can't get this installed properly.    Is there a work-around ? 

Environment: 
- Puppet Enterprise 3.3.2
- CentOS 6.5

Yum info: 

``` ini
yum info redis
Loaded plugins: fastestmirror, security
Loading mirror speeds from cached hostfile
 * base: centos.mirror.ca.planethoster.net
 * epel: mirror.clarkson.edu
 * extras: centos.bhs.mirrors.ovh.net
 * updates: mirror.its.dal.ca
Installed Packages
Name        : redis
Arch        : x86_64
Version     : 2.4.10
Release     : 1.el6
```

**Comment by xcompass** [comment]
I got similar problem on CentOS 6.5. redis.conf was empty and hang at /sbin/service redis start. Kill redis process and break puppet, then rerun puppet. It will generate the correct conf file. Using EPEL and IUS repo.

The log shows: ==> centos65: Notice: /Stage[main]/Redis/File[/etc/redis.conf]/content: content changed '{md5}1b59697dc32ec93399fb1828553e5f97' to '{md5}68b329da9893e34099c7d8ad5cb9c940'

The 68b329da9893e34099c7d8ad5cb9c940 is the empty redis.conf md5. I thought puppet suppose to replace the redis.conf with the one in the module. Why is it empty?

**Comment by xcompass** [comment]
I think I got some clue. It is because the facter redis_version is empty. So there is no condition in redis.conf met and an empty file is generated.

It seems the facter is calculated before puppet execute any statement. And facter uses installed redis version or try to figure it out through yum (in CentOS). Becuase redis package is in their party repo, e.g. EPEL or IUS (2.8.x in my case). Facter couldn't find any package, thus empty version is returned.

My current workaround is to set redis_version_override. It will force facter to use it. Tested on CentOS.

Maybe there should be a default version number for each distro.

**Comment by zeroecco** [comment]
@fsalum I think I have a fix for this. The if block is setting the redis_version but the case statement is overwriting later. If we combine the two it should work (dropping the else at the end of the case):
redis_version = Facter::Util::Resolution.exec('/usr/sbin/redis-server --version')
    if redis_version.nil?
      redis_version = .....
    else
      case redis_version
          when /2\.8\.[0-9]/
              #set version to 2.8
              redis_version = '2.8.x'
          when /2\.6\.[0-9]/
              #set version to 2.6
              redis_version = '2.6.x'
          when /2\.4\.[0-9]/
              #set version to 2.4
              redis_version = '2.4.x'
          when /2\.2\.[0-9]/
              #set version to 2.2
              redis_version = '2.2.x'
      end
    end
    redis_version

**Comment by fsalum** [comment]
@zeroecco I don't think that would work because we need to set the version to that specific A.B.x to use in the template.

What if the redis_version inside the if-block we rename the variable to something else?

        redis_lookup = Facter::Util::Resolution.exec('/usr/bin/redis-server --version')
        if redis_lookup.nil?
            redis_lookup = Facter::Util::Resolution.exec(dpkg+" show redis-server 2> /dev/null | /bin/grep -i 'version:' | /usr/bin/awk '{printf(\"%s\",$2)}' | sort -nr | head -1")
        end

        case redis_lookup
            when /2\.8\.[0-9]/
                #set version to 2.8
                redis_version = '2.8.x'
            when /2\.6\.[0-9]/
                #set version to 2.6
                redis_version = '2.6.x'
            when /2\.4\.[0-9]/
                #set version to 2.4
                redis_version = '2.4.x'
            when /2\.2\.[0-9]/
                #set version to 2.2
                redis_version = '2.2.x'
            else
                redis_version = 'nil'
        end
        redis_version
